# Code created/updated by ChatGPT (GPT-5 Thinking)
# Source: DAI – Cold Day Classifier v1.3 (DR005 – PARAM-ONLY)
# Sanitised for public repo – replace <PLACEHOLDERS> for your system before enabling writes
# Ref: helpers_entities_map.md (Nov 2025)

alias: DAI – Cold Day Classifier v1.3
description: >
  Code created/updated by ChatGPT (GPT-5 Thinking). v1.3 (DR005 – PARAM-ONLY):
  Helper-first source selection (use stored Estimate helper if present) and
  simplified met.no parsing via daily[0] templow (with fallbacks). No logic
  change to thresholds or outputs. Design Ref: DAI + RBC HLD v1.3 (§9.3) and
  DAI – Cold Day Classifier v1.2 DDD (§2, §4). Change History: v1.3 (DR005
  helper-first + daily[0] read); v1.2 (DR005 forecast indexing fix); v1.1
  (CR016 – met.no provider swap); v1.0 (initial release).
triggers:
  - id: t_0610
    trigger: time
    at: "06:10:00"
  - id: t_ha_start_guarded
    trigger: homeassistant
    event: start
conditions: []
actions:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: t_0610
              - condition: and
                conditions:
                  - condition: trigger
                    id: t_ha_start_guarded
                  - condition: time
                    after: "06:00:00"
        sequence:
          - action: weather.get_forecasts
            target:
              entity_id: weather.forecast_brenchley
            data:
              type: daily
            response_variable: fc_daily
          - action: weather.get_forecasts
            target:
              entity_id: weather.forecast_brenchley
            data:
              type: hourly
            response_variable: fc_hourly
          - variables:
              tomorrow: "{{ (now() + timedelta(days=1)).date() }}"
              estimate_helper_raw: "{{ states('input_number.rbc_temperature_estimate_low_c') }}"
              estimate_helper_ok: >-
                {{ estimate_helper_raw not in ['unknown','unavailable',''] and
                   (estimate_helper_raw | float(default=9999)) != 9999 }}
              estimate_helper_c: "{{ estimate_helper_raw | float(0) }}"
              daily_list: >-
                {{ (fc_daily['weather.forecast_brenchley']['forecast']
                    if fc_daily and 'weather.forecast_brenchley' in fc_daily else []) }}
              hourly_list: >-
                {{ (fc_hourly['weather.forecast_brenchley']['forecast']
                    if fc_hourly and 'weather.forecast_brenchley' in fc_hourly else []) }}
              daily_low_direct: |-
                {% set dl = daily_list %}
                {% if dl|length > 0 and dl[0] is mapping %}
                  {{ (dl[0].get('templow')
                      or dl[0].get('temperature_low')
                      or dl[0].get('native_templow')
                      or dl[0].get('native_temperature_low')) | float(9999) }}
                {% else %}9999{% endif %}
              hourly_low: |-
                {% set lows = [] %}
                {% for f in hourly_list if f is mapping %}
                  {% set dt = as_datetime(f.get('datetime')) %}
                  {% if dt and dt.date() == tomorrow %}
                    {% for k in ['temperature','native_temperature'] %}
                      {% if f.get(k) is not none %}
                        {% set _ = lows.append(f.get(k) | float) %}
                      {% endif %}
                    {% endfor %}
                  {% endif %}
                {% endfor %}
                {{ (lows|min) if lows|length > 0 else 9999 }}
              forecast_low_c: >-
                {% if estimate_helper_ok %}{{ estimate_helper_c }}
                {% elif daily_low_direct != 9999 %}{{ daily_low_direct }}
                {% elif hourly_low != 9999 %}{{ hourly_low }}
                {% else %}unknown{% endif %}
              bias_c: "{{ states('input_number.rbc_temp_bias_c') | float(0) }}"
              threshold_c: "{{ states('input_number.dai_cold_temp_threshold_c') | float(5) }}"
              adjusted_min_c: >-
                {% if forecast_low_c != 'unknown' %}
                  {{ (forecast_low_c | float + bias_c) | round(1) }}
                {% else %}unknown{% endif %}
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ forecast_low_c != 'unknown' }}"
                sequence:
                  - action: input_number.set_value
                    target:
                      entity_id: input_number.rbc_temperature_estimate_low_c
                    data:
                      value: "{{ forecast_low_c | float | round(1) }}"
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ adjusted_min_c != 'unknown' }}"
                        sequence:
                          - action: input_number.set_value
                            target:
                              entity_id: input_number.rbc_adjusted_min_temp_c
                            data:
                              value: "{{ adjusted_min_c | float }}"
                          - action: >-
                              input_boolean.turn_{{ 'on' if (adjusted_min_c |
                              float(99)) <= threshold_c else 'off' }}
                            target:
                              entity_id: input_boolean.dai_cold_day_flag
                          - action: input_text.set_value
                            target:
                              entity_id: input_text.dai_cold_day_reason
                            data:
                              value: >-
                                Estimate={{ forecast_low_c | float | round(1)
                                }}°C, Bias={{ bias_c | round(1) }}°C,
                                Adjusted={{ adjusted_min_c }}°C, Threshold={{
                                threshold_c }}°C → ColdDay={{ (adjusted_min_c |
                                float(99)) <= threshold_c }}
                          - action: logbook.log
                            data:
                              name: DAI – Cold Day Classifier
                              message: >-
                                v1.3 (DR005): Helper-first OK; wrote Estimate {{
                                forecast_low_c | float | round(1) }}°C;
                                Adjusted {{ adjusted_min_c }}°C; ColdDay set={{
                                (adjusted_min_c | float(99)) <= threshold_c }}.
                              entity_id: input_number.rbc_adjusted_min_temp_c
                    default:
                      - action: logbook.log
                        data:
                          name: DAI – Cold Day Classifier
                          message: >-
                            v1.3 (DR005): Estimate {{ forecast_low_c }}°C
                            written; adjusted unknown (no bias?).
                          entity_id: input_number.rbc_temperature_estimate_low_c
              - conditions:
                  - condition: template
                    value_template: "{{ forecast_low_c == 'unknown' }}"
                sequence:
                  - action: logbook.log
                    data:
                      name: DAI – Cold Day Classifier
                      message: >-
                        v1.3 (DR005): No forecast or helper estimate available
                        at 06:10; skipped.
                      entity_id: input_text.dai_cold_day_reason
    default:
      - action: logbook.log
        data:
          name: DAI – Cold Day Classifier
          message: Default branch reached; no valid trigger/guard.
          entity_id: input_text.dai_cold_day_reason
mode: single
