# Code created/updated by ChatGPT (GPT-5 Thinking)
# Source: DAI + RBC Framework (Reference – Design-Doc v5.9)
# Sanitised for public repo – replace <PLACEHOLDERS> for your system before enabling writes

alias: DAI - Tariff Desync Watcher v1.1
description: >
  Code created/updated by ChatGPT (GPT-5 Thinking). v1.1 converts all actions to
  Visual-Editor-safe `service` syntax and hardens templates (numeric casts &
  safe defaults). Behaviour unchanged: monitor Import vs Export tariff helpers,
  warn at `warn_min`, escalate at `halt_min`, optional debug notifications.
triggers:
  - id: t_import_change
    trigger: state
    entity_id: input_select.octopus_import_tariff
  - id: t_export_change
    trigger: state
    entity_id: input_select.octopus_export_tariff
  - id: t_5m
    trigger: time_pattern
    minutes: /5
  - id: t_start
    trigger: homeassistant
    event: start
conditions: []
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ import_label == export_label }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ debug_on }}"
            then:
              - data:
                  name: "{{ v_msg_prefix }} • In sync"
                  message: "{{ status_msg }} (OK)"
                action: logbook.log
            else: []
      - conditions:
          - condition: template
            value_template: >-
              {{ import_label != export_label and (age_min | float(0)) > 0 and
              (age_min | float(0)) < (warn_min | float(0)) }}
        sequence:
          - if:
              - condition: template
                value_template: "{{ debug_on }}"
            then:
              - data:
                  name: "{{ v_msg_prefix }} • Observing"
                  message: "{{ status_msg }} (below warn)"
                action: logbook.log
            else: []
      - conditions:
          - condition: template
            value_template: >-
              {{ import_label != export_label and (age_min | float(0)) >=
              (warn_min | float(0)) and (age_min | float(0)) < (halt_min |
              float(0)) }}
        sequence:
          - data:
              name: "{{ v_msg_prefix }} • Warning"
              message: "{{ status_msg }} — Export typically lags Import; monitoring."
            action: logbook.log
          - if:
              - condition: template
                value_template: "{{ debug_on }}"
            then:
              - data:
                  title: "{{ v_msg_prefix }} — Warning"
                  message: "{{ status_msg }}"
                action: notify.<your_device_name_here>
      - conditions:
          - condition: template
            value_template: >-
              {{ import_label != export_label and (age_min | float(0)) >=
              (halt_min | float(0)) }}
        sequence:
          - data:
              name: "{{ v_msg_prefix }} • Escalate"
              message: >-
                {{ status_msg }} — Recommend **conservative export behaviour**
                until Export aligns.
            action: logbook.log
          - if:
              - condition: template
                value_template: "{{ debug_on }}"
            then:
              - data:
                  title: "{{ v_msg_prefix }} — Escalate"
                  message: >-
                    {{ status_msg }} — Suggest conservative export mode if your
                    export automations support it.
                action: notify.<your_device_name_here>
    default:
      - data:
          name: "{{ v_msg_prefix }} • Default"
          message: >-
            No matching branch for trigger='{{ trigger.id }}'. State: {{
            status_msg }}
        action: logbook.log
mode: single
variables:
  import_label: "{{ states('input_select.octopus_import_tariff') }}"
  export_label: "{{ states('input_select.octopus_export_tariff') }}"
  warn_min: "{{ states('input_number.tariff_desync_warn_minutes') | float(30) }}"
  halt_min: "{{ states('input_number.tariff_desync_halt_minutes') | float(180) }}"
  soft_pause_enabled: "{{ is_state('input_boolean.tariff_desync_soft_pause','on') }}"
  debug_on: "{{ is_state('input_boolean.octopus_tariff_autoset_debug','on') }}"
  import_changed_ts: >-
    {{ as_timestamp(states.input_select.octopus_import_tariff.last_changed, 0)
    }}
  export_changed_ts: >-
    {{ as_timestamp(states.input_select.octopus_export_tariff.last_changed, 0)
    }}
  last_flip_ts: "{{ [import_changed_ts, export_changed_ts] | max }}"
  now_ts: "{{ as_timestamp(now()) }}"
  age_min: |-
    {% if import_label not in ['unknown','unavailable',''] and
          export_label not in ['unknown','unavailable',''] and
          import_label != export_label %}
      {{ ((now_ts - last_flip_ts) / 60) | float(0) | round(1) }}
    {% else %}0{% endif %}
  status_msg: >-
    Import='{{ import_label }}' • Export='{{ export_label }}' • DesyncAge='{{
    age_min }} min' • Warn='{{ warn_min }}' • Halt='{{ halt_min }}' •
    SoftPause={{ 'ON' if soft_pause_enabled else 'OFF' }}
  v_msg_prefix: Tariff Desync
