# Code created/updated by ChatGPT (GPT-5 Thinking)
# Source: DAI + RBC Framework (Reference – Design-Doc v5.9)
# Sanitised for public repo – replace <PLACEHOLDERS> for your system before enabling writes

alias: DAI – Free Energy Sessions Controller v3.6 r1
description: >
  Code created/updated by ChatGPT (GPT-5 Thinking). v3.6 r1: Parser-safe
  refactor replacing templated entity references with static IDs. Behaviour
  identical to v3.6 (Option B structural change + End-clear + watchdog).
  Design-Doc: DAI + RBC Framework v5.85 (Oct 2025). Change History: v3.6 r1
  (refactor only); v3.6 (structural change + watchdog). Governance Reference:
  REFAC-ONLY compliance update (service: syntax alignment).
triggers:
  - id: t_session_start
    trigger: calendar
    entity_id: calendar.octopus_energy_<ACCOUNT>_octoplus_free_electricity_session
    event: start
  - id: t_session_end
    trigger: calendar
    entity_id: calendar.octopus_energy_<ACCOUNT>_octoplus_free_electricity_session
    event: end
  - id: t_ha_start
    trigger: homeassistant
    event: start
  - id: t_heartbeat_5m
    trigger: time_pattern
    minutes: /5
  - id: t_watchdog_2m
    trigger: time_pattern
    minutes: /2
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: t_session_start
        sequence:
          - target:
              entity_id: input_boolean.dai_session_override_active
            action: input_boolean.turn_on
          - choose:
              - conditions:
                  - condition: template
                    value_template: >-
                      {{ 'self' not in
                      (states('select.solax_house_charger_use_mode') | lower) }}
                sequence:
                  - target:
                      entity_id: select.solax_house_charger_use_mode
                    data:
                      option: Self Use Mode
                    action: select.select_option
                  - wait_for_trigger:
                      - trigger: state
                        entity_id: select.solax_house_charger_use_mode
                        to: Self Use Mode
                    timeout: "00:00:20"
                    continue_on_timeout: true
                  - delay: "00:00:05"
            default: []
          - target:
              entity_id: number.solax_house_selfuse_nightcharge_upper_soc
            data:
              value: 100
            action: number.set_value
          - target:
              entity_id: input_datetime.last_mode_change
            data:
              datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
            action: input_datetime.set_datetime
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ notify_ok }}"
                sequence:
                  - target:
                      entity_id: input_datetime.dai_last_mode_notify
                    data:
                      datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
                    action: input_datetime.set_datetime
                  - data:
                      title: Free Energy — LIVE
                      message: >-
                        Live session ON → Override ON, Self Use set, Target SoC
                        = 100 %.
                    action: notify.<your_device_name_here>
          - data:
              name: DAI – Free Energy
              entity_id: select.solax_house_charger_use_mode
              message: START ({{ trigger.id }}) → Self Use, cap = 100 %, override = ON.
            action: logbook.log
      - conditions:
          - condition: trigger
            id: t_session_end
        sequence:
          - delay: "00:00:03"
          - target:
              entity_id: input_boolean.dai_session_override_active
            action: input_boolean.turn_off
          - delay: "00:00:02"
          - choose:
              - conditions:
                  - condition: state
                    entity_id: input_boolean.dai_session_override_active
                    state: "on"
                sequence:
                  - target:
                      entity_id: input_boolean.dai_session_override_active
                    action: input_boolean.turn_off
                  - data:
                      name: DAI – Free Energy
                      entity_id: select.solax_house_charger_use_mode
                      message: >-
                        END guard: override still ON after first clear →
                        retrying.
                    action: logbook.log
          - target:
              entity_id: input_datetime.last_mode_change
            data:
              datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
            action: input_datetime.set_datetime
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ notify_ok }}"
                sequence:
                  - target:
                      entity_id: input_datetime.dai_last_mode_notify
                    data:
                      datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
                    action: input_datetime.set_datetime
                  - data:
                      title: Free Energy — ENDED
                      message: >-
                        Live session OFF → Override cleared. Control returns to
                        Planner/Clipping.
                    action: notify.<your_device_name_here>
          - data:
              name: DAI – Free Energy
              entity_id: select.solax_house_charger_use_mode
              message: END ({{ trigger.id }}) → override = OFF. No mode/cap writes.
            action: logbook.log
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: t_ha_start
              - condition: trigger
                id: t_heartbeat_5m
          - condition: template
            value_template: "{{ prehold_today }}"
        sequence:
          - target:
              entity_id: input_boolean.dai_session_override_active
            action: input_boolean.turn_on
          - choose:
              - conditions:
                  - condition: template
                    value_template: >-
                      {{ 'feed' not in
                      (states('select.solax_house_charger_use_mode') | lower) }}
                sequence:
                  - target:
                      entity_id: select.solax_house_charger_use_mode
                    data:
                      option: Feed-in Priority
                    action: select.select_option
                  - wait_for_trigger:
                      - trigger: state
                        entity_id: select.solax_house_charger_use_mode
                        to: Feed-in Priority
                    timeout: "00:00:20"
                    continue_on_timeout: true
                  - delay: "00:00:05"
          - target:
              entity_id: input_datetime.last_mode_change
            data:
              datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
            action: input_datetime.set_datetime
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ notify_ok and trigger.id == 't_ha_start' }}"
                sequence:
                  - target:
                      entity_id: input_datetime.dai_last_mode_notify
                    data:
                      datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
                    action: input_datetime.set_datetime
                  - data:
                      title: Free Energy — Pre-Hold
                      message: >-
                        Event today (not live) → Override ON, Feed-in Priority
                        set. Planner owns SoC floors.
                    action: notify.<your_device_name_here>
          - data:
              name: DAI – Free Energy
              entity_id: select.solax_house_charger_use_mode
              message: >-
                PRE-HOLD ({{ trigger.id }}) → Feed-in Priority, override = ON.
                No cap write (Planner owns).
            action: logbook.log
      - conditions:
          - condition: trigger
            id: t_watchdog_2m
          - condition: state
            entity_id: calendar.octopus_energy_<ACCOUNT>_octoplus_free_electricity_session
            state: "off"
          - condition: state
            entity_id: input_boolean.dai_session_override_active
            state: "on"
        sequence:
          - target:
              entity_id: input_boolean.dai_session_override_active
            action: input_boolean.turn_off
          - data:
              name: DAI – Free Energy
              entity_id: select.solax_house_charger_use_mode
              message: >-
                WATCHDOG → calendar=off but override=on → force-cleared
                override.
            action: logbook.log
    default:
      - data:
          name: DAI – Free Energy
          entity_id: select.solax_house_charger_use_mode
          message: No matching branch executed (default path).
        action: logbook.log
mode: single
variables:
  live_now: >-
    {{ is_state('calendar.octopus_energy_<ACCOUNT>_octoplus_free_electricity_session','on') }}
  next_start_ts: >-
    {% set s = state_attr('calendar.octopus_energy_<ACCOUNT>_octoplus_free_electricity_session','start_time') %}
    {% if s in [none,'unknown','unavailable',''] %}{{ none }}{% else %}{{ as_datetime(s) | as_local }}{% endif %}
  prehold_today: |-
    {{
      (not live_now)
      and (next_start_ts is not none)
      and (next_start_ts.date() == now().date())
      and (now() < next_start_ts)
    }}
  notify_gap_sec: 120
  last_notify_str: "{{ states('input_datetime.dai_last_mode_notify') }}"
  last_notify_ts: >-
    {% set s = last_notify_str %} {% if s in [none,'unknown','unavailable',''] %}0
    {% else %}{{ as_timestamp(strptime(s,'%Y-%m-%d %H:%M:%S')) }}{% endif %}
  notify_ok: "{{ (as_timestamp(now()) - (last_notify_ts|float(0))) > notify_gap_sec }}"
