# Code created/updated by ChatGPT (GPT-5 Thinking)
# Source: DAI – Usage Daily Rolling Accumulator v1.0 (DAI + RBC Framework)
# Sanitised for public repo – replace <PLACEHOLDERS> with your own entity IDs before enabling writes
# Redactions: None (entity names are generic and safe for publication)

alias: DAI – Usage Daily Rolling Accumulator v1.0
description: >
  Code created/updated by ChatGPT (GPT-5 Thinking). Builds a **rolling Daily
  usage (kWh)** by integrating sensor.brenchley_total_load_w once per minute
  across the entire day. Stores into input_number.dai_usage_daily_kwh_rolling
  (rounded to 2dp) and **self-resets at 00:00** so each new day starts from
  zero. Visual-Editor-safe.
triggers:
  - id: t_every_min
    trigger: time_pattern
    minutes: /1
conditions: []
actions:
  - variables:
      hh: "{{ now().hour }}"
      mm: "{{ now().minute }}"
      is_midnight: "{{ hh == 0 and mm == 0 }}"
      p_w_raw: "{{ states('sensor.brenchley_total_load_w') }}"
      p_w: >-
        {{ p_w_raw | float(0) if p_w_raw not in
        ['unknown','unavailable','none',''] else 0 }}
      inc_kwh: "{{ (p_w / 60000) | float(0) }}"
      cur_kwh: "{{ states('input_number.dai_usage_daily_kwh_rolling') | float(0) }}"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ is_midnight }}"
        sequence:
          - action: input_number.set_value
            target:
              entity_id: input_number.dai_usage_daily_kwh_rolling
            data:
              value: 0
          - action: logbook.log
            data:
              name: DAI — Usage Daily Rolling
              message: Midnight reset → 0.00 kWh for {{ now().date() }}.
              entity_id: input_number.dai_usage_daily_kwh_rolling
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ p_w >= 0 }}"
        sequence:
          - action: input_number.set_value
            target:
              entity_id: input_number.dai_usage_daily_kwh_rolling
            data:
              value: "{{ (cur_kwh + inc_kwh) | round(2) }}"
    default:
      - action: logbook.log
        data:
          name: DAI — Usage Daily Rolling
          message: No add (power unavailable/invalid).
          entity_id: input_number.dai_usage_daily_kwh_rolling
mode: single
